language: python
python:
    - "2.7"
    - "3.5"
install: 
    - "pip install -r requirements.txt"
    - "pip install coveralls"
    - "pip install -e ."
script: 
    - 'coverage run --source=stockmarket setup.py test'

after_success:
    coveralls    
